import requests
import bs4
from bs4 import BeautifulSoup
import warnings
import time
import datetime
import json
import pandas as pd
import io
import re
import psycopg2
import quandl
import random
import os
import shutil
import numpy as np
import matplotlib.pyplot as plt
import datetime
from selenium import webdriver

warnings.filterwarnings('ignore')

url="https://www.dividendchannel.com/ex-dividend-calendar/?confirm=1"
finaldata=[]
try:
    outfile=open('../dist/json/dividend.json','r')
    item=json.load(outfile)
    for i in item:
        finaldata.append(i)
except:
    pass

driver = webdriver.Firefox()
driver.get(url)
time.sleep(5)
htmlSource = driver.page_source
soup=BeautifulSoup(htmlSource)
soupstr=str(soup)
t=soup.find_all("table")
for z in t:
    if z.text.find("ExPay")>0:
        h=z.find_all("tr")

        for v in h:
            d=v.find_all("td")
            data={}
            i=0
            for col in d:
                if i==0:
                    strcol=str(col)
                    ss=strcol.find('symbol')
                    if ss!=-1:
                        strcol=strcol[ss+7:ss+7+30]
                        es=strcol.find('"><font')
                        ticker=strcol[:es]
                        data['Ticker']=ticker
                    else:
                        data['Ticker']='-'
                    # tickerpoint=strcol.find("/symbol/")
                    # endpoint=strcol[tickerpoint:].find('">')
                    # data['Ticker']=strcol[tickerpoint+8:endpoint]
                    data['Stock']=col.text
                    tester1=col.text
                    if tester1==None or tester1=='' or tester1==' ':
                        tester1='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                if i==1:
                    data['Type']=col.text
                    tester2=col.text
                    if tester2==None or tester2=='' or tester2==' ':
                        tester2='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                if i==2:
                    data['Dividend']=col.text
                    tester3=col.text
                    if tester3==None or tester3=='' or tester3==' ':
                        tester3='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                if i==3:
                    data['LastPrice']=col.text
                    tester4=col.text
                    if tester4==None or tester4=='' or tester4==' ':
                        tester4='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                if i==4:
                    data['Yield']=col.text
                    tester5=col.text
                    if tester5==None or tester5=='' or tester5==' ':
                        tester5='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                if i==5:
                    data['ExDay']=col.text
                    tester6=col.text
                    if tester6==None or tester6=='' or tester6==' ':
                        tester6='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                if i==6:
                    data['PayDay']=col.text
                    tester7=col.text
                    if tester7==None or tester7=='' or tester7==' ':
                        tester7='NANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANANANANAANA'
                i=i+1
            if len(tester1)<=100 and len(tester2)<=100 and len(tester3)<=100 and len(tester4)<=100 and len(tester5)<=100 and len(tester6)<=100 and len(str(data))>=70:
                # json_data=json.dumps(data)

                finaldata.append(data)




with open('../dist/json/dividend.json', 'w') as outfile:
    json.dump(finaldata, outfile)
